<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Resources\**" />
    <EmbeddedResource Remove="Resources\**" />
    <None Remove="Resources\**" />
    <Page Remove="Resources\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Views\Imgs\a.jpg" />
    <None Remove="Views\Imgs\a.png" />
    <None Remove="Views\Imgs\b.jpg" />
    <None Remove="Views\Imgs\b.png" />
    <None Remove="Views\Imgs\logo.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Logs\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NUnit" Version="4.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Views\Imgs\a.jpg" />
    <Resource Include="Views\Imgs\a.png" />
    <Resource Include="Views\Imgs\b.jpg" />
    <Resource Include="Views\Imgs\b.png" />
    <Resource Include="Views\Imgs\logo.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <None Update="App.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
